metrics_store = "/Users/adam/thesis/realtime-seq/plants-data/metrics.db"
minimum_mapped_bases = 1_000_000
minimum_reads_for_parameter_estimation = 30
minimum_fragments_for_ratio_estimation = 30
thinning_accelerator = 1

[read_processor]
batch_size = 10
target_base_count = 50_000

[[reference_sequences]]
path = "/Users/adam/thesis/realtime-seq/plants-data/GCA_048544455.1_ASM4854445v1_genomic.fna"
expected_ratio = 1

[[reference_sequences]]
path = "/Users/adam/thesis/realtime-seq/plants-data/Rumex_hastatulus.fna"
expected_ratio = 1

[sequencer]
host = "localhost"
port = 9501
name = "MN34570"

[read_until]
host = "127.0.0.1"
port = 8000
depletion_chunks = 2
throttle = 0.1

[read_until.basecaller]
address = "ipc:///tmp/.dorado/dorado-basecall-server.sock"
config = "dna_r10.4.1_e8.2_400bps_5khz_fast"
max_attempts = 3

[read_until.classifier.mappy]
