reference_sequences = [
    "/Users/adam/thesis/realtime-seq/test-data/GCF_904425475.1/GCF_904425475.1_MG1655_genomic.fna"
    # "/Users/adam/thesis/realtime-seq/test-data/Homo_sapiens.GRCh38.dna.chromosome.1.fa"
]
min_coverage = 7
min_read_length = 20

[sequencer]
host = "localhost"
port = 9501
name = "MN34986"

[read_until]
host = "127.0.0.1"
port = 8000
depletion_chunks = 4
throttle = 0.1

[read_until.basecaller]
address = "ipc:///tmp/.guppy/5555"
config = "dna_r10.4.1_e8.2_400bps_5khz_fast"
max_attempts = 3

[read_until.interleaved_bloom_filter]
fragment_length = 100_000
k = 13
hashes = 3
error_rate = 0.1
confidence = 0.95